### ISSUE TITLE
Scam tokens according to the waves community?

### ISSUE THREAD

**Issue by djpnewton** [wavesplatform/waves-community#53]
Is this really about the the *community* thinks are scam tokens.. or is it about what one person believes about trademarks?

My PR to remove a token was closed and locked without any chance for me to discuss it.

**Comment by twiggysmile** [comment]
Hello!

Unfortunately, Zap Token cannot be removed from the spam folder since it duplicates already existing token issued on the Ethereum network. For this reason, it may mislead Waves users.

https://etherscan.io/token/0x6781a0f84c7e9e846dcb84a9a5bd49333067b104
https://coinmarketcap.com/currencies/zap/

During the creation of an asset, you agree that:

i) You will not use the token for fraudulent purposes.
ii) You will not duplicate, fully or in part, the name of an existing cryptocurrency or a well-known company with the aim of misleading users.
iii) You will not use names of states, other administrative units or municipal institutions for the token's name with the aim of misleading users.

![2019-01-16 11 57 59](https://user-images.githubusercontent.com/23609938/51231634-02839280-1986-11e9-9d75-ef7c1d979f63.png)

Failure to observe these points will lead to your token being classified as spam and will be available to search only by ID.

Please create a new asset with the original name. There are a lot of free and unique names. So, please choose and use some of them.

**Comment by djpnewton** [comment]
1) I have not seen that image, where is that from?

2) The clause you site also says "with the aim of misleading users." we certainly dont have that aim, and our usage is targeted at a small geographic area

3) Do you refuse to use dollars in Australia, Canada or New Zealand because the USA used the term first?

Can you stop closing my issues? It makes it hard to discuss the issue
