### ISSUE TITLE
How can I report that my token is not spam?

### ISSUE THREAD

**Issue by kernelpanic2015** [wavesplatform/waves-community#54]
How can I report that my token is not spam?
We have a Company and website
website: https://www.empirecoins.io
Company Name: Empire Coins
Token Name: EMC2
Token Id: FtBaGyd2UBZKApMUt9jrDEM9NtQfG7ca4nGfb2B8psAg
Please I need help

**Comment by twiggysmile** [comment]
Hello!

The provided token cannot be removed from the spam folder since it duplicates the ticker name (EMC2) of already existing cryptocurrency - https://coinmarketcap.com/currencies/einsteinium/

So, the selected name may mislead Waves users.

Please create a new asset with the original name. There are a lot of free and unique names. So, please choose and use some of them.
